const workoutPlan = [
  "Align",
  "Lower Body",
  "Upper Body",
  "Sweat",
  "Rest",
  "Lower Body",
  "Upper Body",
  "Sweat",
  "Lower Body",
  "Core",
  "Upper Body",
  "Rest",
  "Sweat",
  "Core",
  "Upper Body",
  "Buns",
  "Core",
  "Lower Body",
  "Rest",
  "Sweat",
  "Strength Intervals",
  "Sweat",
  "Core / Hardcore",
  "Buns",
  "Drench",
  "Rest",
  "Strength Intervals",
  "Sweat",
  "Sculpt",
  "Sweat",
  "Core",
  "Drench",
  "Rest",
  "Buns",
  "Strength Intervals",
  "Drench",
  "Core / Hardcore",
  "Buns",
  "Sculpt",
  "Rest",
  "Drench",
  "Sweat",
  "Sculpt",
  "Sweat",
  "Core / Hardcore",
  "Buns",
  "Rest",
  "Drench",
  "Strength Intervals",
  "Drench",
  "Buns",
  "Sweat",
  "Core",
  "Rest",
  "Sculpt",
  "Drench",
];

function piyo(startDate, fileTitle) {
  const daysDifference = moment(fileTitle, "YYYY-MM-DD").diff(
    moment(startDate, "YYYY-MM-DD"),
    "days"
  );
  const workoutIndex = daysDifference % workoutPlan.length;
  return `PiYo: ${workoutPlan[workoutIndex]}`;
}

module.exports = piyo;
